apiVersion: v1
kind: Service
metadata:
  name: --clusterName--
  labels:
    app: --clusterName--
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 8080
    name: vmc
  clusterIP: None
  selector:
    app: --clusterName--
  publishNotReadyAddresses: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: --clusterName--
spec:
  selector:
    matchLabels:
      app: --clusterName--
  serviceName: "--clusterName--"
  replicas: --replicaCount--
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: --clusterName--
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - --clusterName--
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
      - name: --clusterName--
        image: --containerImage---
        imagePullPolicy: Always
        ports:
        - containerPort: 3021
          name: intra-node
        - containerPort: 3022
          name: tls-intra-node
        - containerPort: 21211
          name: external-admin
        - containerPort: 21212
          name: external-client
        - containerPort: 5555
          name: replication
        - containerPort: 8080
          name: vmc
        resources:
          requests:
           cpu: --cpuCount--
           memory: --memorySize--
        readinessProbe:
          exec:
            command:
            - test `echo "exec @Ping;" | ../../bin/sqlcmd --output-skip-metadata --output-format=csv`
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
#         Specify 'voltdb start ...' command line args (space separated list)
#         IMPORTANT!!!! VoltDB requires linux kernel feature Transparent Huge Pages (THP) be DISABLED when running VoltDB in PRODUCTION.
#         Uncomment next 2 lines to ignore THP settings on non-production systems.
#          - name: VOLTDB_START_ARGS
#            value: "--ignore=thp"
#          - name: VOLTDB_HEAPMAX
#            value: "3072"
#          - name: VOLTDB_OPTS
#            value: ""
#          - name: JAVA_OPTS
#            value: ""
#       Persistent volume mounts
#       Configuring for maximum performance often requires multiple local disk or ssd, particularly for commmand log and snapshots
#       See our performance guide https://docs.voltdb.com/PerfGuide/
#       Warning: localdisk provisioning is beta in k8s V1.10, support may be limited.
        volumeMounts:
        - name: voltdbroot
          mountPath: /voltdbroot
#        - name: commandlog
#          mountPath: /commandlog
#        - name: commandlogsnapshot
#          mountPath: /commandlogsnapshot
#        - name: exportoverflow
#          mountPath: /exportoverflow
#        - name: snapshots
#          mountPath: /snapshots
  volumeClaimTemplates:
  - metadata:
      name: voltdbroot
    spec:
      #storageClassName:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: --pvolumeSize--
